package com.stadium.app.models.enums;

/**
 * Created by Shamyyoun on 6/4/16.
 */
public enum ReservationsType {
    TEAM_RESERVATIONS, PLAYER_RESERVATIONS,
    ADMIN_TODAY_RESERVATIONS, ADMIN_ACCEPTED_RESERVATIONS,
    ADMIN_NEW_RESERVATIONS, ADMIN_PREVIOUS_RESERVATIONS,
    ADMIN_MY_RESERVATIONS,
}
